### ISSUE TITLE
Gnome system monitor is transparent

### ISSUE THREAD

**Issue by dulex123** [ubuntu/gnome-shell-communitheme#200] opened 2018-06-01 09:43 UTC
OS: Ubuntu 18.04

Running gnome system monitor displays transparent background and every time it gets opened. Very hard to read the processes

**Comment by jim3872** [comment] 2018-06-01 16:03
This i

The issue is with the snap apps. Gnome calculator and system monitor are installed as snaps which don't currently inherit custom shell themes. If you install the non-snap versions you that should get you by.
--

sudo snap remove gnome-system-monitor
sudo apt install gnome-system-monitor

**Comment by clobrano** [comment] 2018-06-03 15:35
closing as duplicate of https://github.com/ubuntu/gtk-communitheme/issues/354

**Closed by clobrano** 2018-06-03 15:35 UTC
