### ISSUE TITLE
Windows names shortened even if already short

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/gnome-shell-communitheme#156] opened 2018-05-01 12:35 UTC
When you have some windows opened and hit the "super" button you can see all of them. When you select any of them, you can see it's title at the bottom. But even if the title is very short, it is still truncated at the end. 
Example on the screenshot. The text should read "Obrazy" but it is "Obr..."
If a title is 3 characters long, it will be truncated to 3 dots.
![zrzut ekranu z 2018-05-01 13-20-22](https://user-images.githubusercontent.com/1629120/39473003-85243276-4d44-11e8-872f-8bed3e6023c9.png)

**Comment by Feichtmeier** [comment] 2018-05-01 15:25
I can't confirm this on my installation 

![screenshot from 2018-05-01 17-24-25](https://user-images.githubusercontent.com/15329494/39479100-8d9dabec-4d64-11e8-9188-fe0e1431bf4c.png)

@madsrh @clobrano can you confirm this?

**Comment by madsrh** [comment] 2018-05-01 19:43
@Feichtmeier Yes +1 I'm seeing this too

**Comment by mivoligo** [comment] 2018-05-01 20:18
I've updated the theme to the one from --edge channel with `snap refresh communitheme --edge` but the issue is still visible.

**Comment by godlyranchdressing** [comment] 2018-05-02 15:08
That doesn't happen on my installation either. Are you using the communitheme session?

**Comment by mivoligo** [comment] 2018-05-02 15:14
Yes, I do. I've tried with normal session and all looks good there.

**Comment by mivoligo** [comment] 2018-05-03 07:59
Here's the screenshot from "normal" Ubuntu session:
![zrzut ekranu z 2018-05-03 08-57-50](https://user-images.githubusercontent.com/1629120/39565537-464be626-4eb0-11e8-872b-0270b1a98f09.png)

**Comment by Feichtmeier** [comment] 2018-05-03 18:08
Maybe that's snap related? Oo I'll that on my families computers check when I am back home tomorrow

**Comment by clobrano** [comment] 2018-05-06 10:56
I can't reproduce this as well :|

**Comment by Paz-it** [comment] 2018-05-08 20:34
I have the same issue .

**Comment by Feichtmeier** [comment] 2018-05-10 09:06
I smell snap.
I can confirm this now on my wifes ubuntu machine which uses the snap installation.
Will take a look at more family member comuters @.@ (yes I converted them all!)

**Comment by Feichtmeier** [comment] 2018-05-10 09:50
Found it... for some reason the class for the window label in the overview is named (yes this is my comment -.-):

  .window-caption { //LABEL ATTACHED TO THE WINDOW AS A TOOLTIP
    spacing: 25px;
    color: green;//$osd_fg_color;
    font-size: 11pt;
    background-color: $osd_bg_color;
    border: 1px solid $osd_borders_color;
    border-radius: $medium_radius;
    padding: 4px 12px;
  }

![screenshot from 2018-05-10 11-50-17](https://user-images.githubusercontent.com/15329494/39863902-53c56bfe-5448-11e8-85f7-c26966f93a64.png)


But sadly this gets overridden by the snap font size.

**Comment by Paz-it** [comment] 2018-05-10 23:46
I this place I have : 
.window-caption {
  spacing: 25px;
  color: #F7F7F7;
  background-color: #2B2929;
  border: 1px solid rgba(255, 255, 255, 0.15);
  border-radius: 6px;
  padding: 4px 12px; }
No font size mentioned... I wonder if I looked at the correct file. it looks VERY different

**Comment by madsrh** [comment] 2018-06-26 00:00
@Feichtmeier Is it something with the interface font that determines how much space should be given to the label?

I'm guessing this is an upstream issue, because the vanilla Gnome session has this issue too. When setting the font larger, it creates too much space:

![untitled-1](https://user-images.githubusercontent.com/3986894/41881342-5a3ba808-78e3-11e8-9fe4-5045a48dc0ae.jpg)

**Comment by madsrh** [comment] 2018-06-26 00:07
https://gitlab.gnome.org/GNOME/gnome-shell/issues/378

**Comment by clobrano** [comment] 2018-06-26 20:51
Closing it now as it is managed by upstream now

**Comment by madsrh** [comment] 2018-06-27 08:54
> Closing it now as it is managed by upstream now

@clobrano I'm reopening this issue with the hope that someone here can fix this before October (notch notch 😉 ). I don't believe it has low priority upstream.

**Comment by Feichtmeier** [comment] 2018-06-30 07:51
Closing this as I have migrated this to the gtk repo

**Closed by Feichtmeier** 2018-06-30 07:51 UTC
Labels: confirmed, upstream
