### ISSUE TITLE
gnome-calculator will sometimes fail to open on communitheme session Ubuntu 18.04

### ISSUE THREAD

**Issue by doctorvik** [ubuntu/gnome-shell-communitheme#181] opened 2018-05-15 05:51 UTC
gnome-calculator will reliably open on either a standard X11 or Wayland session. However with a communitheme session, occasionally, and either an X11 or Wayland sesion it will fail to open with the following error when trying to open from a command line instead of the launcher:
>(gnome-calculator:14692): Gtk-WARNING **: cannot open display: :0

This command is being run as a standard user in a terminal and not as sudo. Sudo won't launch the program either.
one session when it was failing on Wayland and I switched to X11, it would launch gnome-calculator however it would only display the text on the buttons (including the - [] X buttons on the window bar). The rest of the calculator, menubar itself, and window were entirely transparent.

I did not get a screenshot my apologies and it won't reproduce this effect. However, it continues to give the GTK  warning sometimes on X11 and sometimes on wayland.

**Comment by clobrano** [comment] 2018-05-17 20:52
> one session when it was failing on Wayland and I switched to X11, it would launch gnome-calculator however it would only display the text on the buttons (including the - [] X buttons on the window bar). The rest of the calculator, menubar itself, and window were entirely transparent.

this is for sure gtk-communitheme#354, but

> gnome-calculator will reliably open on either a standard X11 or Wayland session. However with a communitheme session, occasionally, and either an X11 or Wayland sesion it will fail to open with the following error when trying to open from a command line instead of the launcher:
>
>    (gnome-calculator:14692): Gtk-WARNING **: cannot open display: :0

is different, even if the root cause might be the same

> This command is being run as a standard user in a terminal and not as sudo. Sudo won't launch the program either.

Wayland does not support running GUI application with sudo from command line

**Comment by clobrano** [comment] 2018-06-02 16:47
I am not sure this might be a communitheme issue, but @doctorvik could you confirm this is reproducible only in communitheme session?

**Comment by clobrano** [comment] 2018-06-26 20:50
This is 24 days waiting for info. I assume that this is the [same problem pointed out](https://github.com/ubuntu/gnome-shell-communitheme/issues/181#issuecomment-389998120) by @Feichtmeier, which has been solved recently and then close this issue.

If anyone thinks otherwise, feel free to open it again

**Closed by clobrano** 2018-06-26 20:50 UTC
Labels: info-needed
