### ISSUE TITLE
System Monitor Title Bar is still default gnome style

### ISSUE THREAD

**Issue by syscl** [ubuntu/gnome-shell-communitheme#148] opened 2018-04-29 20:23 UTC
Hi, 

Nice Ubuntu theme! But I've noticed an issue while launch the system monitor, the screenshot is attached below.
![screenshot from 2018-04-29 15-19-58](https://user-images.githubusercontent.com/11594858/39410644-3f735768-4bc1-11e8-85e9-89ed57c67ee8.png)

syscl

**Comment by Feichtmeier** [comment] 2018-04-29 20:26
@syscl Thanks for reporting issues!
This is caused by the fact that the system-monitor is installed as a snap on 18.04 and snaps only support gtk-common themes at the moment but soon this theme will work on snaps too (I hope)
Closing this now as there have been several issues about this and we can not fix it from our side !
Best regards

**Closed by Feichtmeier** 2018-04-29 20:26 UTC
Labels: invalid
