### ISSUE TITLE
Theme parsing error = Transparent gnome apps

### ISSUE THREAD

**Issue by SycamoreFox** [ubuntu/gnome-shell-communitheme#201] opened 2018-06-01 12:16 UTC
**gnome-calculator** and **gnome-system-monitor** throw GTK warnings, and display transparent windows

![screenshot from 2018-06-01 08-12-37](https://user-images.githubusercontent.com/18396681/40840289-089f5594-6574-11e8-909a-b17ebb13560f.png)
![screenshot from 2018-06-01 08-13-16](https://user-images.githubusercontent.com/18396681/40840293-0a7a5aee-6574-11e8-9bf5-729bb85c8de3.png)
![screenshot from 2018-06-01 08-10-20](https://user-images.githubusercontent.com/18396681/40840296-0d24aa6a-6574-11e8-8715-5fab9b302dd7.png)

**Comment by jim3872** [comment] 2018-06-01 15:33
The issue is with the snap apps. Gnome calculator and system monitor are installed as snaps which don't currently inherit custom shell themes. If you install the non-snap versions you that should get you by.

**Comment by clobrano** [comment] 2018-06-02 16:45
closing as duplicate of https://github.com/ubuntu/gtk-communitheme/issues/354

**Closed by clobrano** 2018-06-02 16:45 UTC
