### ISSUE TITLE
Deactivated symbols on topbar are hardly visible

### ISSUE THREAD

**Issue by ghost** [ubuntu/gnome-shell-communitheme#106] opened 2018-04-11 19:39 UTC
Not sure if this is a gnome-shell issue or an icon-theme issue. Deactivated symbols are very difficult to see on the transparent topbar:
![bildschirmfoto von 2018-04-11 21-35-54](https://user-images.githubusercontent.com/36449926/38639219-d9c078b8-3dd0-11e8-9d3b-cfee6ef99c35.png)

**Comment by Feichtmeier** [comment] 2018-04-12 10:28
Switched a bit from adwaita to suru on white backgrounds and I think this is caused by the grey shadow having almost the same grey as the grey deactivated speaker symbol in suru. 
So we either change the shadow to a different shade in the shell top bar or open an issue on suru and close this.
@clobrano could you point me to the box-shadow underline in the common file? I'll check on my VM then if this could be fixed by a slightly diffrent shadow.
@NusiNusi  this is a very very bright background btw. :)

**Comment by NusiNusi** [comment] 2018-04-12 12:02
@Feichtmeier 
A few of the incoming wallpapers for Ubuntu 18.04 can have a bright top too. Mostly because of the sky they are showing. To be user-friendly we should respect that some people want to use private pictures as their background. We should garanty that the UI stays clearly visible and work-friendly no matter what background they use.
And yes, maybe it is better to change the icons. Letting them white on mute but use a different symbol to show that speakers are deactivated for example.

**Comment by Feichtmeier** [comment] 2018-04-13 18:08
You totally have a point @NusiNusi 
I just wonder if we should "fix" this here or open an issue in the upstream suru repo.
@clobrano would it be possible to adjust the background shadow so grey icons still have a bit more contrast to bright backgrounds?

**Comment by NusiNusi** [comment] 2018-04-13 19:37
IMO this should be fixed by the icon-theme. I already opened two issues in the suru repo and never got an answer. One ticket is more than one month old. Maybe its the best when someone of the communitheme-team could directly ask the maker of the icon-theme.
As long as the topbar stays transparent there is no other solution than changing the icons itself. At least i think so.

**Comment by clobrano** [comment] 2018-04-14 05:47
The icon has a light grey color, so that on hover it can become white. Reducing the initial grey could help without changing the icon. I am not sure about changing the shadow, since @Luxamann idea was to have no label/icon shadow in top panel

**Comment by Feichtmeier** [comment] 2018-04-25 21:02
So it's basically just that one symbol amirite? Maybe we should ask "him" on the suru repo if he can change its color

**Comment by clobrano** [comment] 2018-04-25 21:24
With the new transparencies it should be fixed. On max transparency we still have shadow to define the icon

**Comment by clobrano** [comment] 2018-04-26 13:55
linking this to #125

**Comment by Feichtmeier** [comment] 2018-04-30 14:46
Yes it is fixed after the latest change in the top bar:
![image](https://user-images.githubusercontent.com/15329494/39433405-12a6ce24-4c96-11e8-8c19-99dade55d709.png)
:+1: ty @clobrano

**Closed by Feichtmeier** 2018-04-30 14:46 UTC
Labels: enhancement, question
