### ISSUE TITLE
Dark fonts on dark panel

### ISSUE THREAD

**Issue by otavioschwanck** [Ubuntu/gnome-shell-communitheme#51] opened 2018-02-09 15:49 UTC
![image](https://user-images.githubusercontent.com/9551316/36036058-f3ba98c2-0d9f-11e8-88f9-8ef1c662208d.png)

applications that occur: Slack and Atom.

**Comment by clobrano** [comment] 2018-02-09 18:33
Duplicate of https://github.com/Ubuntu/gtk-communitheme/issues/148

Thanks as well

**Closed by clobrano** 2018-02-09 18:33 UTC
